### ISSUE TITLE
[Spike] O365 Integration

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal-management#447]
In order for us to establish a path to publish the form letters from the portal, we would need to integrate with O365. This card is to spike on the integration to gauge scope of work involved.

**Comment by LindsayYoung** [comment]
Sent initial email to CRT tech team to get the conversation going

**Comment by LindsayYoung** [comment]
Met with Microsoft, it was extremely helpful- looks like the Power Automate tool would be a good fit.
